- name: add repo
  shell: |
    curl https://haproxy.debian.net/bernat.debian.org.gpg | gpg --dearmor > /usr/share/keyrings/haproxy.debian.net.gpg
    echo deb "[signed-by=/usr/share/keyrings/haproxy.debian.net.gpg]" http://haproxy.debian.net bullseye-backports-2.4 main \
    > /etc/apt/sources.list.d/haproxy.list
    apt-get update && apt-get install haproxy=2.4.\* -y

- name: Copy haproxy.cfg
  ansible.builtin.template:
    src: "{{ role_path }}/files/haproxy.cfg"
    dest: /etc/haproxy/haproxy.cfg
