#!/bin/sh
### BEGIN INIT INFO
# Provides:          prometheus
# Required-Start:    $network
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Prometheus at boot time
### END INIT INFO

PROMETHEUS_CMD="/usr/bin/prometheus --config.file=/mnt/data/prometheus/prometheus.yml --storage.tsdb.path=/mnt/data/prometheus/data --storage.tsdb.retention.time=1y"

case "$1" in
  start)
    nohup $PROMETHEUS_CMD > /proc/1/fd/1 2>/proc/1/fd/2 &
    ;;
  stop)
    pkill -f "$PROMETHEUS_CMD"
    ;;
  restart)
    pkill -f "$PROMETHEUS_CMD"
    nohup $PROMETHEUS_CMD > /proc/1/fd/1 2>/proc/1/fd/2 &
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
