---
global:
  scrape_interval: 15s

  external_labels:
    monitor: "test-monitor"

rule_files:
  - "prometheus_rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - monitoring-server:9093

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          [
            "monitoring-server:9100",
            "webserver-1:9100",
            "webserver-2:9100",
            "postgres:9100",
            "haproxy:9100",
            "haproxy:8405"

          ]

  - job_name: "blackbox_http_2xx"
    scheme: https
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          [
            "http://webserver-1",
            "http://webserver-2"
          ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: monitoring-server:9115

