---
- name: Install Nginx on web servers
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create a simple "Hello, World!" HTML page
  ansible.builtin.copy:
    dest: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Hello, World!</title>
          <style>
              body { font-family: Arial, sans-serif; text-align: center; padding-top: 50px; }
          </style>
      </head>
      <body>
          <h1>Hello, World!</h1>
          <p>Welcome to your Nginx server!</p>
      </body>
      </html>
    mode: '0644'

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

