---
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false

  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false

  http_401:
    prober: http
    http:
      valid_status_codes: [401]
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false

  tcp_connect:
    prober: tcp

  ssh_banner:
    prober: tcp
    tcp:
      query_response:
        - expect: "^SSH-2.0-"
  icmp:
    prober: icmp
